### PR TITLE
delete linker override files

### PR DESCRIPTION
**Pull request by PureWeen**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
remove AkavacheSqliteLinkerOverride.cc.pp files as they are no longer needed and are a hold over from package.config anyway

**What is the current behavior? (You can also link to an open issue here)**
if you're using package.config it would include this file into the project

**What is the new behavior (if this is a feature change)?**

*Akavache.Registrations.Start("ApplicationName")*

Should now be used so that the linker file isn't needed

**Does this PR introduce a breaking change?**
Kind of if you're using packages.config

**Please check if the PR fulfills these requirements**
- [ ] The commit follows our guidelines: https://github.com/Akavache/Akavache/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by allenhumphreys** [comment]
I was surprised this change happened in a patch version change and broke the "it just works" nature of the Nuget package for Xamarin.iOS.

**Comment by glennawatson** [comment]
This is a bug fix so it follows semver release protocol. Basically a file that shouldn't be included was.

**Comment by glennawatson** [comment]
https://semver.org/

> PATCH version when you make backwards-compatible bug fixes.

Given this was a backwards compatible bug fix we followed the release exactly to the letter.

**Comment by allenhumphreys** [comment]
Backwards compatible would suggest that it functions the same after the change, but it did not, in fact, continue to function. (Even if we were relying on the file's existence erroneously)

**Comment by glennawatson** [comment]
Discussion over.

**Comment by glennawatson** [comment]
The functions did continue to function the same as before. There was a change in 6.1 to include the new way of using the function mentioned in the description, this is a point release of 6.1 without any API changes.

**Comment by allenhumphreys** [comment]
@glennawatson I'm not trying to be argumentative, but it sounds like the change that happened in 6.1 was meant to be a breaking change, which would've been worthy of a `MAJOR` version change. I probably would've looked closer at what was changed. Thanks @glennawatson! Have a great day :-)

**Comment by glennawatson** [comment]
@allenhumphreys yeah if you made that argument against the PR that did the 6.1 release that may have been a better argument. This project was in a state of flux around that time.

**Pull request merged**
