### PR TITLE
SqliteOperationQueue.Start unintentially creates async void method

### PR DESCRIPTION
**Pull request by jmarolf**
**What kind of change does this PR introduce?**
`new Task(async () =>...`  is interpreted by overload resolution as `new Task(Action)` and therefore creates an `async void` method which will return immediately making the `task.Wait();` in the `Disposable.Create` method unnecessary.  I assume the intention is to actually wait for the task to complete.

**What is the current behavior?**
Currently `Start` with fire off an unobservable background task.  Any exceptions thrown from this async void method are uncatchable and will bring down the host process.

**What is the new behavior (if this is a feature change)?**
Instead we use the result of an async local function.

**Does this PR introduce a breaking change?**
No

**Other information**:
Is it unclear what the expected threading behavior of ` Disposable.Create` is.  If *this* operation can be done asynchronously via `Disposable.Create(async () => ` then we may not need to burn a thread on `task.Wait` and could instead yield the thread until the task completes.

### CODE REVIEW

**Comment by jmarolf** [comment]
Build failed with the following message
```
Error: The assembly 'Cake.PinNuGetDependency, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (0.17.0). 
This assembly need to reference at least Cake.Core version 0.22.0. 
Another option is to downgrade Cake to an earlier version. 
It's not recommended, but you can explicitly opt-out of assembly verification 
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true", 
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
Command exited with code 1
```

**Comment by PureWeen** [comment]
Yea that cake thing is fixed by this PR

https://github.com/akavache/Akavache/pull/384

**Comment by PureWeen** [comment]
Hey @jmarolf   sorry about getting back to you on this so late

I just noticed you modified the same code as this PR
https://github.com/reactiveui/Akavache/pull/407

That I just merged in. Does that PR address your concerns?

**Comment by jmarolf** [comment]
👍

**Pull request closed without merging**
